In [97]:
import pandas as pd

# 교통 소통정보 CSV 불러오기
city_df = pd.read_csv('월별 소통정보 (자치구별-첨두시별).csv', encoding='utf-8')  # 필요 시 encoding='cp949'

# 구조 확인
print(city_df.info())
print(city_df.head(20))

city_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   기준월      1000 non-null   int64
 1   첨두시구분코드  1000 non-null   object
 2   시간대설명    1000 non-null   object
 3   권역코드     1000 non-null   int64
 4   권역코드명    1000 non-null   object
 5   평균속도     1000 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB
None
       기준월 첨두시구분코드       시간대설명  권역코드 권역코드명   평균속도
0   202503      T0  전일 (06~22)   100   종로구  21.21
1   202503      T0  전일 (06~22)   101    중구  19.82
2   202503      T0  전일 (06~22)   102   용산구  26.11
3   202503      T0  전일 (06~22)   103   성동구  24.09
4   202503      T0  전일 (06~22)   104   광진구  23.40
5   202503      T0  전일 (06~22)   105  동대문구  22.83
6   202503      T0  전일 (06~22)   106   중랑구  21.61
7   202503      T0  전일 (06~22)   107   성북구  23.42
8   202503      T0  전일 (06~22)   108   강북구  20.35
9   202503      T0  전일 (06~22)   109   도봉구  21.30
10  202503      T0  전일 (06~22)   110   노원구  21.78
11  202503      T0  전일 (06~22)   111   은평구  20.44
12  202503      T0  전일 (06~22)   112  서대문구  22.60
13  202503      T0  전일 (06~22)   113   마포구  23.30
14  202503      T0  전일 (06~22)   114   양천구  26.20
15  202503      T0  전일 (06~22)   115   강서구  21.58
16  202503      T0  전일 (06~22)   116   구로구  22.19
17  202503      T0  전일 (06~22)   117   금천구  22.84
18  202503      T0  전일 (06~22)   118  영등포구  22.37
19  202503      T0  전일 (06~22)   119   동작구  25.13

        기준월 첨두시구분코드       시간대설명  권역코드 권역코드명   평균속도
0    202503      T0  전일 (06~22)   100   종로구  21.21
1    202503      T0  전일 (06~22)   101    중구  19.82
2    202503      T0  전일 (06~22)   102   용산구  26.11
3    202503      T0  전일 (06~22)   103   성동구  24.09
4    202503      T0  전일 (06~22)   104   광진구  23.40
..      ...     ...         ...   ...   ...    ...
995  202501      T3  오후 (17~19)   120   관악구  22.91
996  202501      T3  오후 (17~19)   121   서초구  23.10
997  202501      T3  오후 (17~19)   122   강남구  20.29
998  202501      T3  오후 (17~19)   123   송파구  21.47
999  202501      T3  오후 (17~19)   124   강동구  20.26

[1000 rows x 6 columns]

In [27]:
import pandas as pd

highway_df = pd.read_csv('서울시설공단_서울도시고속도로 노선별 요일별 속도_20250507.csv', encoding='cp949')

# 데이터 확인
print(highway_df.info())
print(highway_df.head(20))

highway_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년도         96 non-null     int64
 1   월          96 non-null     int64
 2   도로명        96 non-null     object
 3   평일 평균 교통량  96 non-null     int64
 4   평일 평균 속도   96 non-null     float64
 5   일요일(휴일포함)  96 non-null     float64
 6   월요일        96 non-null     float64
 7   화요일        96 non-null     float64
 8   수요일        96 non-null     float64
 9   목요일        96 non-null     float64
 10  금요일        96 non-null     float64
 11  토요일        96 non-null     float64
dtypes: float64(8), int64(3), object(1)
memory usage: 9.1+ KB
None
      년도   월     도로명  평일 평균 교통량  평일 평균 속도  일요일(휴일포함)   월요일   화요일   수요일   목요일  \
0   2024   1    강변북로     219290      48.0       63.1  50.1  50.2  47.3  47.4
1   2024   2    강변북로     218630      42.9       59.4  43.0  45.6  41.3  43.3
2   2024   3    강변북로     227321      46.8       59.1  49.4  49.0  48.0  45.1
3   2024   4    강변북로     227307      44.1       60.1  46.9  42.3  44.7  44.2
4   2024   5    강변북로     223623      44.6       55.9  48.3  42.6  47.7  44.1
5   2024   6    강변북로     226492      43.1       57.8  47.4  43.9  41.8  41.8
6   2024   7    강변북로     221097      43.0       57.7  45.0  42.2  44.0  42.7
7   2024   8    강변북로     222050      41.1       58.7  43.7  40.7  39.7  41.7
8   2024   9    강변북로     218942      39.6       55.1  41.7  38.9  37.7  41.3
9   2024  10    강변북로     225775      42.1       54.2  45.3  40.7  42.2  42.3
10  2024  11    강변북로     222522      44.0       50.8  45.7  42.1  44.1  47.6
11  2024  12    강변북로     223448      43.9       58.5  46.3  43.5  44.2  41.9
12  2024   1  경부고속도로     179976      37.3       49.4  38.5  40.1  37.2  36.9
13  2024   2  경부고속도로     182777      32.4       44.9  32.9  33.6  31.1  33.4
14  2024   3  경부고속도로     187101      34.3       44.4  36.1  35.4  35.5  33.7
15  2024   4  경부고속도로     190650      33.5       45.3  36.2  32.1  35.1  33.4
16  2024   5  경부고속도로     192663      34.5       42.9  36.7  33.3  38.3  34.8
17  2024   6  경부고속도로     192483      33.9       46.0  37.1  34.6  33.0  31.9
18  2024   7  경부고속도로     187354      34.4       44.2  36.2  34.5  35.1  34.0
19  2024   8  경부고속도로     190801      33.1       46.8  35.2  32.8  32.3  33.0

     금요일   토요일
0   44.3  50.1
1   40.7  49.7
2   42.4  51.1
3   42.3  46.5
4   42.2  43.0
5   40.3  46.0
6   40.1  47.8
7   39.8  47.3
8   38.0  47.6
9   39.9  41.6
10  41.0  41.2
11  42.2  49.5
12  33.3  39.7
13  30.0  38.5
14  31.1  38.9
15  30.7  35.6
16  31.1  34.8
17  32.5  37.3
18  31.2  39.4
19  32.7  39.4

,년도,월,도로명,평일 평균 교통량,평일 평균 속도,일요일(휴일포함),월요일,화요일,수요일,목요일,금요일,토요일
0,2024,1,강변북로,219290,48.0,63.1,50.1,50.2,47.3,47.4,44.3,50.1
1,2024,2,강변북로,218630,42.9,59.4,43.0,45.6,41.3,43.3,40.7,49.7
2,2024,3,강변북로,227321,46.8,59.1,49.4,49.0,48.0,45.1,42.4,51.1
3,2024,4,강변북로,227307,44.1,60.1,46.9,42.3,44.7,44.2,42.3,46.5
4,2024,5,강변북로,223623,44.6,55.9,48.3,42.6,47.7,44.1,42.2,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...
91,2024,8,강남순환로,159100,81.0,89.4,82.5,80.7,80.1,81.1,80.6,83.9
92,2024,9,강남순환로,163641,79.9,87.1,80.9,80.0,78.5,80.8,78.5,84.0
93,2024,10,강남순환로,164100,80.5,87.6,81.9,80.2,80.1,79.3,80.2,80.7
94,2024,11,강남순환로,159451,80.3,87.2,81.8,80.2,78.0,81.8,79.1,79.2
95,2024,12,강남순환로,157585,81.8,89.2,83.1,81.1,81.6,81.6,81.3,83.5

In [105]:
# 기준월을 문자열로 변환 후 datetime 형식으로 변환
city_df['일자'] = pd.to_datetime(city_df['기준월'].astype(str) + '01', format='%Y%m%d')

# 확인
print(city_df[['기준월', '일자']].head())

city_df

# 2) 고속도로 진출입 관련 '구'
target_districts = ['서초구', '강남구', '금천구', '송파구', '강동구']

# 3) 해당 자치구만 필터링
new_city_df = city_df[city_df['권역코드명'].isin(target_districts)].copy()

# 4) 필요한 컬럼만 추출
new_city_df = new_city_df[['일자', '권역코드명', '평균속도']]
new_city_df = new_city_df.rename(columns={'권역코드명': '자치구', '평균속도': '자치구_평균속도'})

# 확인
print(new_city_df.tail(20))

      기준월         일자
0  202503 2025-03-01
1  202503 2025-03-01
2  202503 2025-03-01
3  202503 2025-03-01
4  202503 2025-03-01
            일자  자치구  자치구_평균속도
917 2025-01-01  금천구     23.05
921 2025-01-01  서초구     27.00
922 2025-01-01  강남구     24.00
923 2025-01-01  송파구     22.94
924 2025-01-01  강동구     21.79
942 2025-01-01  금천구     24.69
946 2025-01-01  서초구     29.44
947 2025-01-01  강남구     27.03
948 2025-01-01  송파구     24.04
949 2025-01-01  강동구     22.72
967 2025-01-01  금천구     23.12
971 2025-01-01  서초구     26.57
972 2025-01-01  강남구     23.51
973 2025-01-01  송파구     22.74
974 2025-01-01  강동구     21.56
992 2025-01-01  금천구     19.25
996 2025-01-01  서초구     23.10
997 2025-01-01  강남구     20.29
998 2025-01-01  송파구     21.47
999 2025-01-01  강동구     20.26

In [89]:
# highway_df 의 연도 와 월을 합쳐서 '일자' 생성
highway_df['일자'] = pd.to_datetime(highway_df['년도'].astype(str) + '-' + highway_df['월'].astype(str).str.zfill(2) + '-01')

# # 확인
print(highway_df[['일자']].tail())

highway_df


# # 2) 고속도로 관련 필요한 컬럼들 추출 

# 모든 요일 컬럼 포함
cols = ['일자', '도로명', '평일 평균 속도', '일요일(휴일포함)', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일']
highway_clean = highway_df[cols].copy()

# 컬럼명 깔끔하게 정리
highway_clean.columns = ['일자', '도로명', '평일', '일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일']

highway_clean

           일자
91 2024-08-01
92 2024-09-01
93 2024-10-01
94 2024-11-01
95 2024-12-01

           일자    도로명    평일   일요일   월요일   화요일   수요일   목요일   금요일   토요일
0  2024-01-01   강변북로  48.0  63.1  50.1  50.2  47.3  47.4  44.3  50.1
1  2024-02-01   강변북로  42.9  59.4  43.0  45.6  41.3  43.3  40.7  49.7
2  2024-03-01   강변북로  46.8  59.1  49.4  49.0  48.0  45.1  42.4  51.1
3  2024-04-01   강변북로  44.1  60.1  46.9  42.3  44.7  44.2  42.3  46.5
4  2024-05-01   강변북로  44.6  55.9  48.3  42.6  47.7  44.1  42.2  43.0
..        ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
91 2024-08-01  강남순환로  81.0  89.4  82.5  80.7  80.1  81.1  80.6  83.9
92 2024-09-01  강남순환로  79.9  87.1  80.9  80.0  78.5  80.8  78.5  84.0
93 2024-10-01  강남순환로  80.5  87.6  81.9  80.2  80.1  79.3  80.2  80.7
94 2024-11-01  강남순환로  80.3  87.2  81.8  80.2  78.0  81.8  79.1  79.2
95 2024-12-01  강남순환로  81.8  89.2  83.1  81.1  81.6  81.6  81.3  83.5

[96 rows x 10 columns]

In [73]:
highway_df

,년도,월,도로명,평일 평균 교통량,평일 평균 속도,일요일(휴일포함),월요일,화요일,수요일,목요일,금요일,토요일,일자
0,2024,1,강변북로,219290,48.0,63.1,50.1,50.2,47.3,47.4,44.3,50.1,2024-01-01
1,2024,2,강변북로,218630,42.9,59.4,43.0,45.6,41.3,43.3,40.7,49.7,2024-02-01
2,2024,3,강변북로,227321,46.8,59.1,49.4,49.0,48.0,45.1,42.4,51.1,2024-03-01
3,2024,4,강변북로,227307,44.1,60.1,46.9,42.3,44.7,44.2,42.3,46.5,2024-04-01
4,2024,5,강변북로,223623,44.6,55.9,48.3,42.6,47.7,44.1,42.2,43.0,2024-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,2024,8,강남순환로,159100,81.0,89.4,82.5,80.7,80.1,81.1,80.6,83.9,2024-08-01
92,2024,9,강남순환로,163641,79.9,87.1,80.9,80.0,78.5,80.8,78.5,84.0,2024-09-01
93,2024,10,강남순환로,164100,80.5,87.6,81.9,80.2,80.1,79.3,80.2,80.7,2024-10-01
94,2024,11,강남순환로,159451,80.3,87.2,81.8,80.2,78.0,81.8,79.1,79.2,2024-11-01
95,2024,12,강남순환로,157585,81.8,89.2,83.1,81.1,81.6,81.6,81.3,83.5,2024-12-01

In [119]:
# 자치구 데이터 정제 (중복 제거)
new_city_df = new_city_df.groupby(['일자', '자치구'], as_index=False)['자치구_평균속도'].mean()

# 병합
merged_df = pd.merge(new_city_df, highway_clean, on='일자', how='inner')

# 병합된 데이터 저장
merged_df.to_csv('병합된_교통속도_데이터.csv', index=False, encoding='utf-8-sig')

# 확인
print(f"총 데이터 수: {len(merged_df)}")

merged_df

총 데이터 수: 200

,일자,자치구,자치구_평균속도,도로명,평일,일요일,월요일,화요일,수요일,목요일,금요일,토요일,key
0,2024-07-01,강남구,21.725,강변북로,43.0,57.7,45.0,42.2,44.0,42.7,40.1,47.8,1
1,2024-07-01,강남구,21.725,경부고속도로,34.4,44.2,36.2,34.5,35.1,34.0,31.2,39.4,1
2,2024-07-01,강남구,21.725,내부순환로,53.7,64.3,56.6,52.6,54.5,53.3,50.5,55.4,1
3,2024-07-01,강남구,21.725,동부간선도로,52.3,59.6,54.1,51.4,53.4,52.2,49.7,51.5,1
4,2024-07-01,강남구,21.725,북부간선도로,43.4,50.4,45.6,44.5,45.1,41.0,39.4,43.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2024-12-01,송파구,22.100,동부간선도로,53.1,61.9,57.5,54.7,55.5,54.2,53.6,54.9,1
196,2024-12-01,송파구,22.100,북부간선도로,46.8,58.0,48.3,46.9,47.3,46.3,45.0,49.8,1
197,2024-12-01,송파구,22.100,분당수서로,43.1,60.8,45.2,44.1,42.9,41.3,41.4,49.8,1
198,2024-12-01,송파구,22.100,올림픽대로,46.8,62.1,49.7,46.9,47.1,44.7,45.7,52.9,1
199,2024-12-01,송파구,22.100,강남순환로,81.8,89.2,83.1,81.1,81.6,81.6,81.3,83.5,1